# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\x12\x07\x62ooking\";\n\x05Order\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0e\n\x06places\x18\x03 \x01(\x05\"C\n\x08Response\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\x05\x12\x14\n\x0corder_places\x18\x02 \x01(\x05\x12\x0f\n\x07success\x18\x03 \x01(\x08\x32\x39\n\x06\x42ooker\x12/\n\nOrderPlace\x12\x0e.booking.Order\x1a\x11.booking.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDER']._serialized_start=26
  _globals['_ORDER']._serialized_end=85
  _globals['_RESPONSE']._serialized_start=87
  _globals['_RESPONSE']._serialized_end=154
  _globals['_BOOKER']._serialized_start=156
  _globals['_BOOKER']._serialized_end=213
# @@protoc_insertion_point(module_scope)
